### ISSUE TITLE
Quantity increment and price precision per order

### ISSUE THREAD

**Issue by leeduan** [provenance-io/ats-smart-contract#22]
## Handle non integer price per unit per order

Need to support a non integer order price when dealing with a contract instance where the base and quote denoms are significantly different.

## Problem Definition

hash exists in 10^9 of its base unit nhash. Each hash is tradable in the cents per stable coin unit. This makes it impossible to support if we’re requiring whole number price per unit.

e.g. an order to bid for 1 hash is really a bid for 1,000,000,000 nhash for 15 centistablecoin. This has a price per unit of 0.000000015.

## Proposal

Handle two fields upon instantiation:

* price_precision: the smallest per share price allowable
* quantity_increment: the base multiple of each order

If price_precision * quantity_increment is an int and at least 1, trades will work for whole numbers on both the base and quote denom.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ktalley-figure** [comment]
_Base is an overloaded term here. **Order base** = base in QUOTE/BASE order pair, **Base Unit** = smallest unit of measurement for the marker._

Is this a presentation layer issue instead? In the example above, the order quote is centistablecoin, the order base is nhash, and the order price is 15. 

Using decimals allows for a price in terms of hash, but the calculations will always be in the base unit, in this case nhash. In addition, only base units of coin (nhash, not hash) are sent to and from the contract. Lastly, price_precision and quantity_increment would need to be set for each allowable quote denom in the contract instance. Unless I am misunderstanding, the additional complexity only benefits presenting in terms of hash rather than nhash?

**Comment by dpederson-figure** [comment]
Can we add examples for these values? - assuming $0.15 for 1,000,000,000 nhash.

**Comment by ktalley-figure** [comment]
that yields a price of 66666666.666666667 nhash/cent which is not possible. By enforcing calculations in terms of the respective base units, rounding and fractions are avoided. The smallest possible price is 1nhash/1cent.

**Comment by iramiller** [comment]
> Is this a presentation layer issue instead?
The denom metadata is intended for display purposes only according to the SDK ... so I would say this is all about configuring your UI to make something that is easy for the user to understand...

The base unit of a marker/coin is indivisible which is why we started with something so small (nano) which indicates the limit of our precision in calculations for hash.

**Comment by leeduan** [comment]
I am only talking about working with the base unit here. Agreed that denim metadata is needed to present a nicer UI.

The example I keep referring to here is nhash and a centistablecoin because those are the base units of the two coins we will be trading here and there’s a significant difference in value between the two denim’s in base form.

For an order book to function where the bids and asks orders can operate on whole number of base coins, you have to properly define both a quantity increment and minimum price per unit that allows for whole coins to be bilaterally settled.

In our case, let’s assume a single hash which is 1_000_000_000 nhash is worth 1 cent which is 1 centistablecoin:

```
hash | nhash | price per nhash | stablecoin equivalent
-- | -- | -- | --
1 | 1,000,000,000 | 0.000000001 | 1
2 | 2,000,000,000 | 0.000000001 | 2
3 | 3,000,000,000 | 0.000000001 | 3
4 | 4,000,000,000 | 0.000000001 | 4
5 | 5,000,000,000 | 0.000000001 | 5
6 | 6,000,000,000 | 0.000000001 | 6
7 | 7,000,000,000 | 0.000000001 | 7
8 | 8,000,000,000 | 0.000000001 | 8
9 | 9,000,000,000 | 0.000000001 | 9
10 | 10,000,000,000 | 0.000000001 | 10
11 | 11,000,000,000 | 0.000000001 | 11
12 | 12,000,000,000 | 0.000000001 | 12
13 | 13,000,000,000 | 0.000000001 | 13
14 | 14,000,000,000 | 0.000000001 | 14
15 | 15,000,000,000 | 0.000000001 | 15
16 | 16,000,000,000 | 0.000000001 | 16
17 | 17,000,000,000 | 0.000000001 | 17
18 | 18,000,000,000 | 0.000000001 | 18
19 | 19,000,000,000 | 0.000000001 | 19
20 | 20,000,000,000 | 0.000000001 | 20
21 | 21,000,000,000 | 0.000000001 | 21
22 | 22,000,000,000 | 0.000000001 | 22
23 | 23,000,000,000 | 0.000000001 | 23
24 | 24,000,000,000 | 0.000000001 | 24
25 | 25,000,000,000 | 0.000000001 | 25
```

If the smart contract allows a price per nhash to become as small as 0.000000001 per unit, we must enforce a quantity interval of 1_000_000_000 so that centstablecoin must be transferred as a whole unit since it’s already in its base form.

You will notice that the min price per unit is the inverse exponent of the quantity interval.

**Comment by leeduan** [comment]
> Unless I am misunderstanding, the additional complexity only benefits presenting in terms of hash rather than nhash?

This complexity has nothing to do with presentation. It is required given the fact that as currently built where price has to be an int, you cannot pay less than a centistablecoin for a nhash at which point you are saying each 1_000_000_000 nhash or single hash is worth that many cents which isn’t the value of the token.
